-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    app_name TEXT NOT NULL,
    app_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TEST CASES TABLE
CREATE TABLE IF NOT EXISTS public.test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'txt' NOT NULL, -- txt, csv, xlsx
    commands TEXT NOT NULL,           -- Raw natural language steps
    cached_json JSONB,                -- Cached translated JSON actions (optional)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. EXECUTIONS (RUNS) TABLE
CREATE TABLE IF NOT EXISTS public.executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
    test_id BIGINT REFERENCES public.test_cases(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL,             -- 'Passed', 'Failed', 'Running', 'Pending'
    duration INTEGER DEFAULT 0 NOT NULL, -- Total duration in seconds
    browser TEXT DEFAULT 'Chromium' NOT NULL,
    headless BOOLEAN DEFAULT true NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. EXECUTION STEP LOGS TABLE
CREATE TABLE IF NOT EXISTS public.execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT REFERENCES public.executions(id) ON DELETE CASCADE NOT NULL,
    step_number INTEGER NOT NULL,
    action TEXT NOT NULL,             -- 'goto', 'click', 'fill', 'verify_text', etc.
    raw_command TEXT,                 -- Natural language command representation
    status TEXT NOT NULL,             -- 'passed', 'failed', 'running', 'pending'
    error_message TEXT,
    screenshot_url TEXT,              -- Link to Supabase Storage file
    duration_ms INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. OPENTELEMETRY SPANS TABLE
CREATE TABLE IF NOT EXISTS public.telemetry_spans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT REFERENCES public.executions(id) ON DELETE CASCADE,
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    parent_span_id TEXT,
    service_name TEXT DEFAULT 'backend-server',
    name TEXT NOT NULL,
    kind TEXT DEFAULT 'INTERNAL',
    duration_ms INTEGER DEFAULT 0,
    status_code TEXT DEFAULT 'OK',
    attributes JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execution_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_spans ENABLE ROW LEVEL SECURITY;

-- Simple permissive policies for our prototype
CREATE POLICY "Allow all actions for authenticated users" ON public.projects FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.test_cases FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.executions FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.execution_logs FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all actions for authenticated users" ON public.telemetry_spans FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow public access" ON public.telemetry_spans FOR ALL TO public USING (true) WITH CHECK (true);

